// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>BookaFlight</b><br>
 * Generated     : <b>2019/09/06 4:38:18 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  September 06, 2019
 * @author Mayakkannan.r
 */
public abstract class BookaFlightHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * PROCEEDsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : PROCEED
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_proceeDsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_proceeDsubmit"));
	}
	/**
	 * PROCEEDsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : PROCEED
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_proceeDsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_proceeDsubmit"), anchor, flags);
	}
	
	/**
	 * SEARCHsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : SEARCH
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_searcHsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_searcHsubmit"));
	}
	/**
	 * SEARCHsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : SEARCH
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_searcHsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_searcHsubmit"), anchor, flags);
	}
	
	/**
	 * BookingMade: with default state.
	 *		.title : Booking made
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-home/book-flight-control.jsp?flightnumber=VB046&w ...
	 */
	protected DocumentTestObject document_bookingMade() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bookingMade"));
	}
	/**
	 * BookingMade: with specific test context and state.
	 *		.title : Booking made
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-home/book-flight-control.jsp?flightnumber=VB046&w ...
	 */
	protected DocumentTestObject document_bookingMade(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bookingMade"), anchor, flags);
	}
	
	/**
	 * VacationBookingOnlineFlightBooking: with default state.
	 *		.title : Vacation Booking online flight booking
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-home/
	 */
	protected DocumentTestObject document_vacationBookingOnline() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_vacationBookingOnline"));
	}
	/**
	 * VacationBookingOnlineFlightBooking: with specific test context and state.
	 *		.title : Vacation Booking online flight booking
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-home/
	 */
	protected DocumentTestObject document_vacationBookingOnline(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_vacationBookingOnline"), anchor, flags);
	}
	
	/**
	 * flightNumberUI: with default state.
	 *		.id : flightNumberUI
	 * 		.title : 
	 * 		.class : Html.P
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightNumberUI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightNumberUI"));
	}
	/**
	 * flightNumberUI: with specific test context and state.
	 *		.id : flightNumberUI
	 * 		.title : 
	 * 		.class : Html.P
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightNumberUI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightNumberUI"), anchor, flags);
	}
	
	/**
	 * FlightReservationNumber: with default state.
	 *		.id : FlightReservationNumber
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightReservationNumber() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightReservationNumber"));
	}
	/**
	 * FlightReservationNumber: with specific test context and state.
	 *		.id : FlightReservationNumber
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightReservationNumber(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightReservationNumber"), anchor, flags);
	}
	
	/**
	 * Flight: with default state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_flight() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_flight"));
	}
	/**
	 * Flight: with specific test context and state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_flight(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_flight"), anchor, flags);
	}
	
	/**
	 * flyingfrom: with default state.
	 *		.text : From Departing City Amsterdam (AMS) Bangalore (BLR) Barcelona (BCN) Edinburgh (E ...
	 * 		.id : fromDropDown
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : flyingfrom
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_flyingfrom() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_flyingfrom"));
	}
	/**
	 * flyingfrom: with specific test context and state.
	 *		.text : From Departing City Amsterdam (AMS) Bangalore (BLR) Barcelona (BCN) Edinburgh (E ...
	 * 		.id : fromDropDown
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : flyingfrom
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_flyingfrom(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_flyingfrom"), anchor, flags);
	}
	
	/**
	 * flyingto: with default state.
	 *		.text : To Destination Amsterdam (AMS) Bangalore (BLR) Barcelona (BCN) Edinburgh (EDI)
	 * 		.id : toDropDown
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : flyingto
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_flyingto() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_flyingto"));
	}
	/**
	 * flyingto: with specific test context and state.
	 *		.text : To Destination Amsterdam (AMS) Bangalore (BLR) Barcelona (BCN) Edinburgh (EDI)
	 * 		.id : toDropDown
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : flyingto
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_flyingto(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_flyingto"), anchor, flags);
	}
	
	/**
	 * passengerSelector: with default state.
	 *		.text : Autofill Customer David Ling Rohit
	 * 		.id : passengerSelector
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_passengerSelector() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_passengerSelector"));
	}
	/**
	 * passengerSelector: with specific test context and state.
	 *		.text : Autofill Customer David Ling Rohit
	 * 		.id : passengerSelector
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_passengerSelector(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_passengerSelector"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * cardholdersname: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : cardholdersname
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cardholdersname() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardholdersname"));
	}
	/**
	 * cardholdersname: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : cardholdersname
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_cardholdersname(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_cardholdersname"), anchor, flags);
	}
	
	/**
	 * from: with default state.
	 *		.id : from
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : from
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_from() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_from"));
	}
	/**
	 * from: with specific test context and state.
	 *		.id : from
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : from
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_from(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_from"), anchor, flags);
	}
	
	

	protected BookaFlightHelper()
	{
		setScriptName("BookaFlight");
	}
	
}

