// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.cucumbervBooking;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>VBookingSteps</b><br>
 * Generated     : <b>2019/09/10 6:11:54 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  September 10, 2019
 * @author Mayakkannan.r
 */
public abstract class VBookingStepsHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : Chrome
	 * 		.processName : chrome.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * BoardPassengersubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Board Passenger
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_boardPassengersubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_boardPassengersubmit"));
	}
	/**
	 * BoardPassengersubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Board Passenger
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_boardPassengersubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_boardPassengersubmit"), anchor, flags);
	}
	
	/**
	 * CheckInsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Check-in
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_checkInsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_checkInsubmit"));
	}
	/**
	 * CheckInsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : Check-in
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_checkInsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_checkInsubmit"), anchor, flags);
	}
	
	/**
	 * PROCEEDsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : PROCEED
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_proceeDsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_proceeDsubmit"));
	}
	/**
	 * PROCEEDsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : PROCEED
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_proceeDsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_proceeDsubmit"), anchor, flags);
	}
	
	/**
	 * SEARCHsubmit: with default state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : SEARCH
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_searcHsubmit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_searcHsubmit"));
	}
	/**
	 * SEARCHsubmit: with specific test context and state.
	 *		.id : 
	 * 		.type : submit
	 * 		.value : SEARCH
	 * 		.title : 
	 * 		.class : Html.INPUT.submit
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_searcHsubmit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_searcHsubmit"), anchor, flags);
	}
	
	/**
	 * Verifiedbutton: with default state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_verifiedbutton() 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_verifiedbutton"));
	}
	/**
	 * Verifiedbutton: with specific test context and state.
	 *		.id : 
	 * 		.type : button
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.BUTTON
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject button_verifiedbutton(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("button_verifiedbutton"), anchor, flags);
	}
	
	/**
	 * AdministrationMenu: with default state.
	 *		.title : Administration menu
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-admin/checkin-signin.jsp
	 */
	protected DocumentTestObject document_administrationMenu() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_administrationMenu"));
	}
	/**
	 * AdministrationMenu: with specific test context and state.
	 *		.title : Administration menu
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-admin/checkin-signin.jsp
	 */
	protected DocumentTestObject document_administrationMenu(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_administrationMenu"), anchor, flags);
	}
	
	/**
	 * BookFlight: with default state.
	 *		.title : Book Flight
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-home/book-flight.jsp?tripType=f&flyingfrom=STN&fl ...
	 */
	protected DocumentTestObject document_bookFlight() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bookFlight"));
	}
	/**
	 * BookFlight: with specific test context and state.
	 *		.title : Book Flight
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-home/book-flight.jsp?tripType=f&flyingfrom=STN&fl ...
	 */
	protected DocumentTestObject document_bookFlight(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_bookFlight"), anchor, flags);
	}
	
	/**
	 * PassengerBoarding: with default state.
	 *		.title : Passenger Boarding
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-admin/passenger-boarding.jsp?reservation-no=A0001 ...
	 */
	protected DocumentTestObject document_passengerBoarding() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_passengerBoarding"));
	}
	/**
	 * PassengerBoarding: with specific test context and state.
	 *		.title : Passenger Boarding
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-admin/passenger-boarding.jsp?reservation-no=A0001 ...
	 */
	protected DocumentTestObject document_passengerBoarding(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_passengerBoarding"), anchor, flags);
	}
	
	/**
	 * PassengerCheckin: with default state.
	 *		.title : Passenger Checkin
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-admin/passenger-checkin-list.jsp?reservation-no=A ...
	 */
	protected DocumentTestObject document_passengerCheckin() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_passengerCheckin"));
	}
	/**
	 * PassengerCheckin: with specific test context and state.
	 *		.title : Passenger Checkin
	 * 		.class : Html.HtmlDocument
	 * 		.url : http://localhost:8090/vbooking-admin/passenger-checkin-list.jsp?reservation-no=A ...
	 */
	protected DocumentTestObject document_passengerCheckin(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("document_passengerCheckin"), anchor, flags);
	}
	
	/**
	 * flightCost: with default state.
	 *		.id : flightCost
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightCost() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightCost"));
	}
	/**
	 * flightCost: with specific test context and state.
	 *		.id : flightCost
	 * 		.title : 
	 * 		.class : Html.DIV
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightCost(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightCost"), anchor, flags);
	}
	
	/**
	 * flightNumberUI: with default state.
	 *		.id : flightNumberUI
	 * 		.title : 
	 * 		.class : Html.P
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightNumberUI() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightNumberUI"));
	}
	/**
	 * flightNumberUI: with specific test context and state.
	 *		.id : flightNumberUI
	 * 		.title : 
	 * 		.class : Html.P
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightNumberUI(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightNumberUI"), anchor, flags);
	}
	
	/**
	 * FlightReservationNumber: with default state.
	 *		.id : FlightReservationNumber
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightReservationNumber() 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightReservationNumber"));
	}
	/**
	 * FlightReservationNumber: with specific test context and state.
	 *		.id : FlightReservationNumber
	 * 		.title : 
	 * 		.class : Html.SPAN
	 * 		.classIndex : 0
	 */
	protected GuiTestObject html_flightReservationNumber(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("html_flightReservationNumber"), anchor, flags);
	}
	
	/**
	 * gh_demo_calendar: with default state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://localhost:8090/vbooking-home/graphics/new/gh_demo_calendar.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_gh_demo_calendar() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_gh_demo_calendar"));
	}
	/**
	 * gh_demo_calendar: with specific test context and state.
	 *		.alt : 
	 * 		.id : 
	 * 		.src : http://localhost:8090/vbooking-home/graphics/new/gh_demo_calendar.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_gh_demo_calendar(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_gh_demo_calendar"), anchor, flags);
	}
	
	/**
	 * logo: with default state.
	 *		.alt : logo
	 * 		.id : 
	 * 		.src : http://localhost:8090/vbooking-home/graphics/new/gh_demo_vb_banner.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_logo() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_logo"));
	}
	/**
	 * logo: with specific test context and state.
	 *		.alt : logo
	 * 		.id : 
	 * 		.src : http://localhost:8090/vbooking-home/graphics/new/gh_demo_vb_banner.png
	 * 		.title : 
	 * 		.class : Html.IMG
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject image_logo(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("image_logo"), anchor, flags);
	}
	
	/**
	 * Flight: with default state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_flight() 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_flight"));
	}
	/**
	 * Flight: with specific test context and state.
	 *		.id : 
	 * 		.value : 
	 * 		.title : 
	 * 		.class : Html.LABEL
	 * 		.classIndex : 0
	 */
	protected GuiTestObject label_flight(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("label_flight"), anchor, flags);
	}
	
	/**
	 * _DavidThomson: with default state.
	 *		.text :    David Thomson  
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/passenger-boarding.jsp?reservation-no=A0001 ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link__DavidThomson() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__DavidThomson"));
	}
	/**
	 * _DavidThomson: with specific test context and state.
	 *		.text :    David Thomson  
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/passenger-boarding.jsp?reservation-no=A0001 ...
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link__DavidThomson(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link__DavidThomson"), anchor, flags);
	}
	
	/**
	 * MainMenu: with default state.
	 *		.text : Main menu
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/checkin-signin.jsp
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_mainMenu() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mainMenu"));
	}
	/**
	 * MainMenu: with specific test context and state.
	 *		.text : Main menu
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/checkin-signin.jsp
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_mainMenu(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_mainMenu"), anchor, flags);
	}
	
	/**
	 * PassengerBoarding: with default state.
	 *		.text : Passenger boarding
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/checkin-signin.jsp?menu=boarding-select
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_passengerBoarding() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_passengerBoarding"));
	}
	/**
	 * PassengerBoarding: with specific test context and state.
	 *		.text : Passenger boarding
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/checkin-signin.jsp?menu=boarding-select
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 2
	 */
	protected GuiTestObject link_passengerBoarding(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_passengerBoarding"), anchor, flags);
	}
	
	/**
	 * PassengerCheckIn: with default state.
	 *		.text : Passenger check-in
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/checkin-signin.jsp?menu=checkin-select
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_passengerCheckIn() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_passengerCheckIn"));
	}
	/**
	 * PassengerCheckIn: with specific test context and state.
	 *		.text : Passenger check-in
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/checkin-signin.jsp?menu=checkin-select
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 1
	 */
	protected GuiTestObject link_passengerCheckIn(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_passengerCheckIn"), anchor, flags);
	}
	
	/**
	 * VB043: with default state.
	 *		.text : VB043
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/boarding-select.jsp?flight-number=VB043
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_vB043() 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_vB043"));
	}
	/**
	 * VB043: with specific test context and state.
	 *		.text : VB043
	 * 		.id : 
	 * 		.href : http://localhost:8090/vbooking-admin/boarding-select.jsp?flight-number=VB043
	 * 		.title : 
	 * 		.class : Html.A
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected GuiTestObject link_vB043(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("link_vB043"), anchor, flags);
	}
	
	/**
	 * flyingfrom: with default state.
	 *		.text : From Departing City Amsterdam (AMS) Bangalore (BLR) Barcelona (BCN) Edinburgh (E ...
	 * 		.id : fromDropDown
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : flyingfrom
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_flyingfrom() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_flyingfrom"));
	}
	/**
	 * flyingfrom: with specific test context and state.
	 *		.text : From Departing City Amsterdam (AMS) Bangalore (BLR) Barcelona (BCN) Edinburgh (E ...
	 * 		.id : fromDropDown
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : flyingfrom
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_flyingfrom(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_flyingfrom"), anchor, flags);
	}
	
	/**
	 * flyingto: with default state.
	 *		.text : To Destination Amsterdam (AMS) Bangalore (BLR) Barcelona (BCN) Edinburgh (EDI)
	 * 		.id : toDropDown
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : flyingto
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_flyingto() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_flyingto"));
	}
	/**
	 * flyingto: with specific test context and state.
	 *		.text : To Destination Amsterdam (AMS) Bangalore (BLR) Barcelona (BCN) Edinburgh (EDI)
	 * 		.id : toDropDown
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : flyingto
	 * 		.classIndex : 1
	 */
	protected SelectGuiSubitemTestObject list_flyingto(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_flyingto"), anchor, flags);
	}
	
	/**
	 * passengerSelector: with default state.
	 *		.text : Autofill Customer David Ling Rohit
	 * 		.id : passengerSelector
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_passengerSelector() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_passengerSelector"));
	}
	/**
	 * passengerSelector: with specific test context and state.
	 *		.text : Autofill Customer David Ling Rohit
	 * 		.id : passengerSelector
	 * 		.title : 
	 * 		.class : Html.SELECT
	 * 		.name : 
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject list_passengerSelector(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("list_passengerSelector"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0"), anchor, flags);
	}
	
	/**
	 * HtmlTable_0: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"));
	}
	/**
	 * HtmlTable_0: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_htmlTable_0_2(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_htmlTable_0_2"), anchor, flags);
	}
	
	/**
	 * ReservationsForFlightVB043Status: with default state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_reservationsForFlightVB0() 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_reservationsForFlightVB0"));
	}
	/**
	 * ReservationsForFlightVB043Status: with specific test context and state.
	 *		.id : 
	 * 		.title : 
	 * 		.class : Html.TABLE
	 * 		.caption : 
	 * 		.classIndex : 0
	 */
	protected StatelessGuiSubitemTestObject table_reservationsForFlightVB0(TestObject anchor, long flags) 
	{
		return new StatelessGuiSubitemTestObject(
                        getMappedTestObject("table_reservationsForFlightVB0"), anchor, flags);
	}
	
	/**
	 * apiComment: with default state.
	 *		.id : api
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : api-comment
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_apiComment() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_apiComment"));
	}
	/**
	 * apiComment: with specific test context and state.
	 *		.id : api
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : api-comment
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_apiComment(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_apiComment"), anchor, flags);
	}
	
	/**
	 * from: with default state.
	 *		.id : from
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : from
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_from() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_from"));
	}
	/**
	 * from: with specific test context and state.
	 *		.id : from
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : from
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_from(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_from"), anchor, flags);
	}
	
	/**
	 * passportID: with default state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : passportID
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_passportID() 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_passportID"));
	}
	/**
	 * passportID: with specific test context and state.
	 *		.id : 
	 * 		.type : text
	 * 		.title : 
	 * 		.class : Html.INPUT.text
	 * 		.name : passportID
	 * 		.classIndex : 0
	 */
	protected TextGuiTestObject text_passportID(TestObject anchor, long flags) 
	{
		return new TextGuiTestObject(
                        getMappedTestObject("text_passportID"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point ReservationsForFlightVB043Stat_grid object in the SUT.
	 */
	protected IFtVerificationPoint ReservationsForFlightVB043Stat_gridVP() 
	{
		return vp("ReservationsForFlightVB043Stat_grid");
	}
	protected IFtVerificationPoint ReservationsForFlightVB043Stat_gridVP(TestObject anchor)
	{
		return vp("ReservationsForFlightVB043Stat_grid", anchor);
	}
	
	

	protected VBookingStepsHelper()
	{
		setScriptName("cucumbervBooking.VBookingSteps");
	}
	
}

